# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_train.ipynb.

# %% auto 0
__all__ = ['train_tree_models']

# %% ../nbs/01_train.ipynb 3
def train_tree_models(X_train, X_test, folds, seed):
    pass
